export const AVAILABLE_INDICATORS: string[] = [
  "Accelerator Oscillator (AO)",
  "Average True Range (ATR)",
  "Awesome Oscillator (AC)",
  "Average Directional Index (ADX)",
  "Bollinger Bands (BB)",
  "Chaikin Oscillator",
  "Commodity Channel Index (CCI)",
  "Connor's RSI (CRSI)",
  "Donchian Channels (DC)",
  "Exponential Moving Average(EMA)",
  "Exponential Weighted Moving Average (EWMA)",
  "Moving Average Convergence Divergence (MACD)",
  "Pivot Point Levels (classic/woodie/camarilla/fibonacci)",
  "Rate of change (ROC)",
  "Relative Strength Index (RSI)",
  "Simple Moving Average (SMA)",
  "Smoothed Moving Average (SMMA)",
  "SuperTrend MTF (ST MTF)",
  "Stochastic Oscillator (KD)",
  "Wilder's Smoothed Moving Average (WEMA)",
  "Welles Wilder's Smoothing Average (WWS)",
  "Weighted Moving Average (WMA)",
  "Parabolic Stop and Reverse (PSAR)",
  "Volume Profile",
];
