#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
yellow="\033[1;33m"
reset="\033[0m"

if [ -z "$VERSION_EXECUTED" ]; then
  export VERSION_EXECUTED="true"
else
  echo "The update version script was executed on this commit"
  exit 0
fi

printf "\033[1;33m#\n"
printf "# Running ng build and linter... \n#"
printf "\033[0m\n"
npx ng build  && npx pretty-quick --pattern "src/**/*.*(ts,html,scss)" --staged  && ng lint --fix

printf "\033[1;33m#\n"
printf "# Updating project version... \n#"
printf "\033[0m\n"
branch=$(git symbolic-ref --short HEAD)
if [[ $branch == "angular" ]]; then
  git pull origin $branch --rebase
  git fetch origin $branch
  git merge origin/$branch
  npm run deploy:tag patch
  git push --follow-tags
else
  echo "no"
fi

if [ -z "$VERSION_EXECUTED" ]; then
  echo "The update version script was not executed on this commit"
  exit 1
fi