#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
yellow="\033[1;33m"
reset="\033[0m"

if [ -z "$VERSION_EXECUTED" ]; then
  export VERSION_EXECUTED="true"
else
  echo "El script de versión ya se ejecutó en este push."
  exit 0
fi

printf "\033[1;33m#\n"
printf "# Ejecutando el ng build y pasando el linter... \n#"
printf "\033[0m\n"
npx ng build  && npx pretty-quick --pattern "src/**/*.*(ts,html,scss)" --staged  && ng lint --fix

printf "\033[1;33m#\n"
printf "# Elevamos versionado del proyecto \n#"
printf "\033[0m\n"
branch=$(git symbolic-ref --short HEAD)
if [[ $branch == "test-husky" ]]; then
  git fetch
  git pull --rebase
  git fetch origin $branch
  git merge origin/$branch
  npm run deploy:tag patch
  sleep 5
  git push --follow-tags
else
  echo "no"
fi

if [ -z "$VERSION_EXECUTED" ]; then
  echo "El script de versión no se ejecutó en este commit."
  exit 1
fi